title: Introduction to Web Scraping
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ubc-library-rc/web-scraping/\">View workshop content in GitHub</a>"
